import type { Metadata } from 'next';
import { BookShell } from '@/components/Book/BookShell';
import { book, findArticle } from '@/lib/book-toc';
import Article from './article.mdx';

export const metadata: Metadata = {
  title: `§0.1 Where Data Comes From | ${book.title}`,
  description:
    'How modern business data is generated by customer behavior, operations, digital systems, physical environments, language, and AI workflows.',
};

export default function Page() {
  return (
    <BookShell slug="ch00-1-what-is-d3m" book={book} findArticle={findArticle}>
      <Article />
    </BookShell>
  );
}
